### ISSUE TITLE
Link to "extended filters" 404s

### ISSUE THREAD

**Issue by rhys-vdw** [LeoECSCommunity/ecslite#1]
https://github.com/LeoECSCommunity/ecslite/blob/77b43b2ff7cb97cad41b1f0c4a189ab3d5449ef5/README.md?plain=1#L286

**Comment by Talkyn** [comment]
The correct link is: [https://github.com/LeoECSCommunity/ecslite-extendedfilters](https://github.com/LeoECSCommunity/ecslite-extendedfilters)

**Comment by Chillu1** [comment]
> 

Sorry for the super late replay (GH notifs should be fixed now)

Planning to change all links to new correct community ones this week
